from typing import Annotated, List, TypedDict
from dataclasses import dataclass
import operator

# The Finding dataclass provides a structured way to represent security or logic issues.
# Using a dataclass makes it easy to pass around and ensures consistency across different agents.
@dataclass
class Finding:
    file: str
    line: int
    severity: str
    category: str
    description: str

# ReviewState is the 'source of truth' for our LangGraph.
# It defines the schema of the state object that is passed from node to node.
class ReviewState(TypedDict):
    # Inputs: These are provided when the graph is first invoked.
    repo_url: str
    pr_number: int
    base_sha: str
    head_sha: str

    # Diff Reader results: The local path to the cloned repo and the diffs to be analyzed.
    repo_path: str
    raw_diff: str
    file_diffs: List[dict]  # Each dict contains 'filename' and 'diff'

    # Findings: This is where we collect all the issues identified by our agents.
    # Why Annotated[List[Finding], operator.add]?
    # In LangGraph, if multiple parallel nodes update the same key, the default behavior 
    # is to overwrite the value. By using Annotated with operator.add, we tell LangGraph 
    # to MERGE the results (concatenate the lists) instead of overwriting.
    # This is essential for our parallel security and logic review agents.
    findings: Annotated[List[Finding], operator.add]

    # Test Results: The raw output from the Dockerized test runner (e.g., pytest output).
    test_results: str

    # Draft Review: The synthesized markdown review generated by the review_writer agent.
    draft_review: str

    # Human-in-the-loop fields: Stores the decision and any feedback from the dashboard.
    action: str         # Expected values: "approve" or "reject"
    human_comment: str
